<?php
namespace bee\server;
/**
 * Created by PhpStorm.
 * User: VigoXu
 * Date: 2016/2/19
 * Time: 10:28
 */
class CronServer extends BaseServer
{
    protected $timerFile; //定时器配置文件路径
    public function onReceive(\swoole_server $server, $fd, $fromId, $data)
    {
        $this->send($fd, 'Not Allowed');
    }

    public function init()
    {
        $this->config['serverd']['worker_num'] = 1;
        $this->config['serverd']['task_worker_num'] = 0;
    }

    public function onWorkerStart(\swoole_server $server, $workerId)
    {
        require  __DIR__ . '/../App.php';
        \App::getInstance();
        if ($workerId == 0) {
            $this->tick(1000, array($this, 'timer'));
        }
        parent::onWorkerStart($server, $workerId); // TODO: Change the autogenerated stub
    }

    public function timer()
    {
        $config = array();
        foreach ($config as $row) {
            $process = new Process();
            $process->start();
            $process->wait();
        }
    }

    public static function parseCronFile($file)
    {
        $file = new \SplFileObject($file, 'r');
        foreach ($file as $row) {
            $row = rtrim($row);
            $row = preg_replace('/\s+/', ' ', $row);
            if ($row{0} == '#') {
                continue; //注释
            }

        }
    }
    public static function parseWakeup($file)
    {
        $str = file_get_contents($file);
        $str = str_replace('  ', ' ', trim($str));
        $argv = explode(' ', $str);
        $argc = count($argv);

        if($argc == 5){
            //5个参数只支持到分钟，秒默认就是0了
            $names = array('minute', 'hour', 'day', 'month', 'week');
            $wakeup = array(
                'second' => array(
                    array('op' => 'eq', 'v1' => 0)
                )
            );
        }else if($argc == 6){
            //6个参数支持到秒
            $names = array('second', 'minute', 'hour', 'day', 'month', 'week');
            $wakeup = array();
        }else{
            return false;
        }

        foreach($argv as $pos => $val){
            $options = explode(',', $val);
            $name = $names[$pos];
            foreach($options as $val){
                if($val == '*'){//任意值
                    $item = array(
                        'op' => 'any',
                    );
                }else if(is_numeric($val)){//相等
                    $item = array(
                        'op' => 'eq',
                        'v1' => $val,
                    );
                }else if(preg_match('/^(\d+)\-(\d+)$/', $val, $matches)){//范围
                    $item = array(
                        'op' => 'range',
                        'v1' => $matches[1],
                        'v2' => $matches[2],
                    );
                }else if(preg_match('/^\*\/(\d+)$/', $val, $matches)){//取模
                    $item = array(
                        'op' => 'mod',
                        'v1' => $matches[1],
                    );
                }else{
                    return false;
                }

                $wakeup[$name][] = $item;
            }
        }

        return $wakeup;
    }

}